### ISSUE TITLE
This sample not similar with apps from Playstore :(

### ISSUE THREAD

**Issue by ztuning** [navisens/android-mapbox-motiondna-integration#2]
I need some example which dont need GPS or internet for tracking user, because in this example i have to turn on gps and internet to make it work

**Comment by ztuning** [comment]
how i can detect when user turning ?
because motionDna.motion.motionType only showing FIDGETING and FORWARD

**Comment by ztuning** [comment]
how i can draw the red dot ?

**Comment by jamesgrantham** [comment]
Hi there, 
Let me address your questions one at a time.

1. GPS is necessary under any circumstances where you want our SDK to establish your position in a global (lat/lon) frame. Otherwise you will need to set location manually using the setLocation() calls in our SDK. If you only need cartesian you can get those directly from the local location.x and y values in our MotionDna callback.

2. Turning can be determined using the heading value we provide, There is currently no text or enum provided to indicate this movement characteristic.

3. Mapbox API makes it difficult to change the appearance of their default user location dot. You would need to consult the MapBox documentation for guidance on that if it is possible. Our own store app uses the Google Maps api which allows for fairly easy customization of map markers. You would need to consult with their documentation as well for details on styling ([link](https://developers.google.com/maps/documentation/android-sdk/marker))
